# Session 5: Introduction to Numpy & Scikit Image

**Resources:**

* [SciPy](https://scipy.org)
* [Scipy Lectures](https://scipy-lectures.org)
* [NumPy](https://numpy.org)

In [1]:
import matplotlib.pyplot as plt

### How to use a function?

In [2]:
import numpy as np
np.linspace?

### Viewing the source

In [3]:

np.linspace??

### ? will work both in functions and variables

In [9]:
a = "SciPy is awesome ;)"
a?

# NumPy

In [10]:
# Within IPython notebook, add multiple print capabilities
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## NumPy arrays

An array can contain:
* Values of an experiment/simulation at discrete time steps
* A signal recorded by a measurement device, e.g. sound wave
* The pixels of an image, grey-level or colour
* 3-D data measured at different X-Y-Z positions, e.g. MRI scan
* …

In [11]:
import numpy as np
a = np.array([0, 1, 2, 3])

In [12]:
np.shape(a)

(4,)

### NumPy is memory efficient container that provides fast numerical operations

In [13]:
L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2

194 µs ± 2.63 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
915 ns ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
L

range(0, 1000)

### Reference documentation
On the web: http://docs.scipy.org/

In [15]:
# Interactive help
np.array?

In [16]:
# Looking for some stuff
np.lookfor('create array') 

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.char.array
    Create a `chararray`.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.from_dlpack
    Create a NumPy array from an object implementing the ``__dlpack__``
numpy.rec.fromarrays
    Create a record array from a (flat) list of arrays
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.rec.fromfile
    Create an array from binary file data
numpy.rec.fromstring
    Create a record array from binary data
numpy.lib.Arrayterator
    Buffered iterator for big 

In [17]:
# Looking for something when some parts of the word are known
np.con*?

### Manual creation of arrays

#### 1D

In [18]:
# Create 1D array
a = np.array([0, 1, 2, 3])
print("Array ", a)

# Print dimensions of array
print("\nNumber of dimension ", a.ndim)

# Print shape of array
print("\nShape of the array ", a.shape)

# Print the lenght of the array
print("\nLenght of array ", len(a))


Array  [0 1 2 3]

Number of dimension  1

Shape of the array  (4,)

Lenght of array  4


#### 2D, 3D...

In [19]:
# Create 2x3 array
b = np.array([[0, 1, 2], [3, 4, 5]]) 
print("2x3array \n", b)

# Print array dimensions
print("\n2x3 array dimensions ", b.ndim)

#Print array shape
print("\n2x3 array shape ", b.shape)

# Print length of 2x3 array (the first dimension)
print("\nLenght of 2x3 array ", len(b))
print("\nLenght (first dimension) of 2x3 array ", len(b[0]))
print("\nLenght (second dimension) of 2x3 array ", len(b[1]))

b[0]
b[1]

2x3array 
 [[0 1 2]
 [3 4 5]]

2x3 array dimensions  2

2x3 array shape  (2, 3)

Lenght of 2x3 array  2

Lenght (first dimension) of 2x3 array  3

Lenght (second dimension) of 2x3 array  3


array([0, 1, 2])

array([3, 4, 5])

In [20]:
# Create 3x2x3 array
b = np.array([[[0, 1, 2], [3, 4, 5]], 
              [[6, 7, 8], [9, 10, 11]], 
              [[12, 13, 14], [15, 16, 17]]]) 
print("3x2x3 array \n", b)

# Print array dimensions
print("\n3x2x3 array dimensions ", b.ndim)

#Print array shape
print("\n3x2x3 array shape ", b.shape)

# Print length of 3x2x3 array (the first dimension)
print("\nFirst dimension of 3x2x3 array ", len(b[0]))
print("\nSecond dimension of 3x2x3 array ", len(b[1]))
print("\nThird dimension of 3x2x3 array ", len(b[2]))

print("\nFirst dimension \n", b[0])
print("\nFirst dimension \n", b[1])
print("\nFirst dimension \n", b[2])

3x2x3 array 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

3x2x3 array dimensions  3

3x2x3 array shape  (3, 2, 3)

First dimension of 3x2x3 array  2

Second dimension of 3x2x3 array  2

Third dimension of 3x2x3 array  2

First dimension 
 [[0 1 2]
 [3 4 5]]

First dimension 
 [[ 6  7  8]
 [ 9 10 11]]

First dimension 
 [[12 13 14]
 [15 16 17]]


### Creating arrays

#### np.arange: enter data evenly spaced
Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

In [21]:
a = np.arange(10) # 0 .. n-1 
a

print("")

b = np.arange(0, 10, 2) # start, end (exclusive), step
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

#### np.linspace: enter data by points
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval `[start, stop]`.

The endpoint of the interval can optionally be excluded.

In [22]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

print("")

d = np.linspace(0, 1, 5, endpoint=False)
d

print("")

e = np.linspace(0, 1, 5, endpoint=True)
e

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

array([0. , 0.2, 0.4, 0.6, 0.8])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Other common array creation functions

#### np.ones

In [23]:
# Creates an array filled with ones, passing a tuple of the size
print("2D array filled with ones")
a = np.ones((3, 3)) 
a

print("\n\n3D array filled with ones")

b = np.ones((3, 3, 3))
b

2D array filled with ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])



3D array filled with ones


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### np.zeros

In [24]:
# Fill up an array with zeros
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

#### np.eye

In [25]:
# Returns a 2-D array with ones on the diagonal and zeros elsewhere
c = np.eye(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.diag
Extract a diagonal or construct a diagonal array.

In [26]:
d = np.diag(np.array([1, 1, 1, 1, 1]))
d

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### np.random

In [27]:
# Random set between 0-1
a = np.random.rand(4)       
a  

# Random with Gaussian distribution
b = np.random.randn(4)    
print("\n", b)   

array([0.33246936, 0.69881995, 0.56333726, 0.2713515 ])


 [-1.34371385 -0.02437727 -0.14453586  2.10334651]


## Understanding arrays: k3d

We will install the **k3d** library, which allows to visualize arrays in 3D. Due to the fact that we cannot create interactive plots in Google Colab, we will use Jupyter Notebook in local. 

**WARNING** the below commands [will not work in Google Colab](https://github.com/K3D-tools/K3D-jupyter/issues/220). Might work in Binder, but better on local.

In [28]:
# Install in your environment (venv or conda)
!pip install k3d
#!conda install -c conda-forge k3d

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.0/23.0 MB 3.8 MB/s eta 0:00:0000:0100:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.7/74.7 kB 888.4 kB/s eta 0:00:00a 0:00:01


In [32]:
%matplotlib inline
import numpy as np
import k3d

plot = k3d.plot()

b = np.ones((1, 1, 1))

line = k3d.voxels(b, width=1, scaling = [1, 1, 1])

# iadd method, iterates over voxel
plot += line
plot.display()

In [33]:
import k3d

plot = k3d.line([[0, 0, 0],
                 [1, 1, 1]])

plot.display()

In [34]:
%matplotlib inline
import numpy as np
import k3d

plot = k3d.plot()

b = np.array([[[18, 1, 2], [3, 4, 5]], 
              [[6, 7, 8], [9, 10, 11]], 
              [[12, 13, 14], [15, 16, 17]]])

voxel = k3d.voxels(b, width=1, scaling = [1, 1, 1])

# iadd method, iterates over voxel
plot += voxel
plot.display()

### In class exercise: 3D representations

Try to add and represent another dimension to make a 3x3x3 array using k3d

In [35]:
%matplotlib inline
import numpy as np
import k3d

plot = k3d.plot()

b = np.array([[[18, 1, 2], [3, 4, 5], [3, 4, 5]], 
              [[6, 7, 8], [9, 10, 11], [3, 4, 5]], 
              [[12, 13, 14], [15, 16, 17], [3, 4, 5]]])

voxel = k3d.voxels(b, width=1, scaling = [1, 1, 1])

# iadd method, iterates over voxel
plot += voxel
plot.display()

In [36]:
b.shape

## NumPy data types

NumPy has five main type of datatypes. But always the default data for any function (np.zeros, etc.) is floating point:

* Integer
* Float
* Boolean
* Complex
* String


In [37]:
# Integer
a = np.array([1, 2, 3])
a.dtype

In [38]:
# Float
b = np.array([1., 2., 3.])
b.dtype

In [39]:
# Changing data type
c = np.array([1, 2, 3], dtype=float)
c.dtype

In [40]:
# Complex
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

In [41]:
# Bool
e = np.array([True, False, False, True])
e.dtype

In [42]:
# Strings (containing max the letters of the longest word)
f = np.array(['Bonjoursdfsdfsdfds', 'Hello', 'Hallo'])
f.dtype      


## Basic array visualization with Matplotlib



In [43]:
%matplotlib inline  

In [44]:
import matplotlib.pyplot as plt

### 1D array plotting

In [45]:
# Create a linear array from 0 to 3, with 20 steps
x = np.linspace(0, 3, 20)

# Create a linear array from 0 to 9, with 20 steps
y = np.linspace(0, 9, 20)

# Plot the line x, y
plt.plot(x,y)       

# Plot the dots x, y
plt.plot(x,y, 'o')    

In [46]:
x

In [47]:
y

### 2D array plotting
Due to their structure, 2D arrays needs to be plotted as images. There is no need to panic. Let's go step by step.

In [48]:
# Let's create a Gaussian image of 30x30
image = np.random.randn(30, 30)

In [49]:
image

In [51]:
# Let's create a Gaussian image of 30x30
image = np.random.randn(30, 30)

# Let's plot the image with imshow, and select a colormap
plt.imshow(image, cmap=plt.cm.gray)    

# Let's add a colorbar as an index
plt.colorbar()

#### Where can I find more color maps?

You can find a complete source of colormaps [here](https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html)

### In class exercise: change the colormap

Change the colormap in the image to be visualized with one of the available matplotlib colormaps.

In [52]:
# Let's create a Gaussian image of 30x30
image = np.random.randn(30, 30)

# Let's plot the image with imshow, and select a colormap
plt.imshow(image, cmap=plt.cm.viridis)    

# Let's add a colorbar as an index
plt.colorbar() 

## NumPy indexing

Another recap from the previous sessions. Remember that indices always in NumPy begin at O.

![alt text](https://scipy-lectures.org/_images/numpy_indexing.png)

### Access items of array

In [231]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [232]:
a[0], a[2], a[-1]

(0, 2, 10)

### Reverse a sequence

In [41]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Multidimensional arrays

Indexes in multidimensional arrays are tupes of integers.

In 2D, the first dimension corresponds to rows, the second to columns.
F
or multidimensional `a` or `a[0]` is interpreted by taking all elements in the unspecified dimensions.

#### Indexing

In [233]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [234]:
# Second line, second column
a[2, 1]

0

In [44]:
# Change for number 99 in Third line, Second column
a[2, 1] = 99 
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 99,  2]])

In [45]:
# Retrieve second line
a[1]

array([0, 1, 0])

#### Slicing
By default, the three slice components are not required: by default, start is 0, end is the last and step is 1

In [46]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# [start:end:step]
a[0:11:2] 

array([ 0,  2,  4,  6,  8, 10])

In [48]:
# The last index is never included!!!!!
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# By default, start is 0, end is the last and step is 1.
a[1:3]
print("\n")
a[::2]
print("\n")
a[3:]

array([1, 2])

array([ 0,  2,  4,  6,  8, 10])

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# Combination of assignment and slicing
a[1:4] = -4
a
print("\n")
a[::4] = 99
a

array([ 0, -4, -4, -4,  4,  5,  6,  7,  8,  9, 10])

array([99, -4, -4, -4, 99,  5,  6,  7, 99,  9, 10])

## Copies vs. views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use 

`np.may_share_memory()` to check if two arrays share the same memory block. Note however, that this uses heuristics and may give you false positives.

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [53]:
np.may_share_memory(a, b)

True

In [54]:
# When we change an index in the view
b[0] = 12
b

array([12,  2,  4,  6,  8])

In [55]:
# The original is modified as well
a

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [56]:
# We need to create a copy() to put changes that are not reflected in the original
d = a.copy()
d

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
d[0] = 0
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [59]:
# The copy is in a different memory allocation
np.may_share_memory(a, d)

False

## Fancy or Advanced array indexing
NumPy arrays can be indexed with slices, but as well with boolean or integer arrays (masks). This method creates copies rather than views.

### Mask with boolean array

In [235]:
# We start with getting a seed and a random integer array
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [236]:
# Create a Boolean array when the residuals of a/3 are 0
a % 3 == 0

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [237]:
# Create a Boolean mask when the residuals of a/3 are 0
mask = (a % 3 == 0)

# Extract a sub-array with the mask
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a           

array([ 3,  0,  9,  6,  0, 12])

### Mask with integer array

In [64]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
# Indexing by position
# [2, 3, 2, 4, 2] is a Python list
b = a[[2, 3, 2, 4, 2]]
b

array([20, 30, 20, 40, 20])

Some more fancy indexing:

![alt text](https://scipy-lectures.org/_images/numpy_fancy_indexing.png)

In [ ]:
0
1
2
3

In [242]:
# Let's create a Gaussian image of 30x30
image = np.random.randn(10, 15)

In [255]:
image

array([[-5.16647925e-01, -1.89071666e-01, -4.16198015e-01,
         7.24657658e-01, -6.89960677e-01,  4.86414475e-01,
         8.51518950e-01,  4.86249326e-01, -8.34239851e-01,
         1.34499246e+00, -6.78212679e-01,  4.26435074e-01,
        -7.53334794e-01, -1.74411025e+00,  2.25750266e-01],
       [ 2.87035165e-01, -7.74409606e-02,  2.76068497e-01,
        -6.48410888e-01, -7.37464837e-01, -1.68090099e-01,
         1.90927681e+00,  8.14814541e-01, -5.19991754e-01,
         5.58713205e-01, -4.78364660e-01, -4.57260787e-01,
         8.59284008e-01, -5.25264645e-01, -1.67563463e+00],
       [-9.06494701e-01,  8.84152062e-02,  1.28007821e-01,
         1.24161652e+00, -7.16025798e-01,  7.31465736e-01,
         4.25966750e-01, -1.49013772e-01,  8.35843902e-01,
         4.92118903e-01, -8.62308487e-01,  1.07168393e+00,
        -1.22090192e+00,  5.96154331e-02,  2.44416199e-03],
       [ 4.24635721e-01, -7.25433480e-01, -3.49433856e-02,
        -1.40620027e-01,  9.97088367e-01, -7.95914693

In [256]:
def print_elems(arr):
    nrows = arr.shape[0]
    ncols = arr.shape[1]
    for i in range(nrows):
        for j in range(ncols):
            print(arr[i,j])

In [254]:
image[0][0]

-0.5166479247981497

In [257]:
print_elems(image)

-0.5166479247981497
-0.1890716664357128
-0.416198015130148
0.7246576582394498
-0.6899606773138658
0.48641447526861514
0.8515189504847083
0.48624932610831123
-0.8342398506717849
1.344992456622238
-0.6782126793411518
0.4264350744400753
-0.7533347935974722
-1.744110250641094
0.2257502662458201
0.28703516469482443
-0.07744096055993933
0.27606849724284316
-0.6484108883064816
-0.7374648374587585
-0.16809009862191446
1.909276809266566
0.8148145412513252
-0.5199917540975635
0.5587132048474234
-0.4783646604432103
-0.45726078713830676
0.8592840082646755
-0.5252646451556335
-1.6756346341845954
-0.9064947005743282
0.08841520620200595
0.12800782111610085
1.2416165181585397
-0.7160257975174191
0.7314657358201054
0.42596674984978417
-0.14901377221550174
0.8358439021819729
0.4921189029137968
-0.8623084869368738
1.071683929782794
-1.2209019198961333
0.059615433090329545
0.0024441619892351415
0.4246357208598569
-0.7254334803985123
-0.0349433855520906
-0.14062002701591825
0.9970883670936515
-0.7959146932

In [244]:
image.shape[1]

15

In [258]:
image[0]

array([-0.51664792, -0.18907167, -0.41619802,  0.72465766, -0.68996068,
        0.48641448,  0.85151895,  0.48624933, -0.83423985,  1.34499246,
       -0.67821268,  0.42643507, -0.75333479, -1.74411025,  0.22575027])